begin;
create extension if not exists pgtap with schema extensions;
-- Supabase CLI connects as postgres; PostgreSQL 17 records this membership
-- with SET FALSE. Enable role assumption only inside this rolled-back test.
grant move2_vs1_worker to postgres with set true;
select no_plan();
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at) values
('91600000-0000-4000-8000-000000000001','authenticated','authenticated','durable-owner@example.test','{"provider":"email","providers":["email"]}','{"name":"Durable Owner"}',now(),now()),
('91600000-0000-4000-8000-000000000002','authenticated','authenticated','durable-other@example.test','{"provider":"email","providers":["email"]}','{"name":"Durable Other"}',now(),now());
insert into public.actors(id,kind,name,operator_profile_id,operator_label) values('91600000-0000-4000-8000-0000000000aa','AI_AGENT','Durable Test AI','91600000-0000-4000-8000-000000000001','SYNTHETIC_TEST');
create temporary table fixture as select (select actor_id from public.actor_memberships where profile_id='91600000-0000-4000-8000-000000000001' and role='OWNER') subject;
grant select on fixture to authenticated,move2_vs1_worker;
create temporary table baseline as select (select count(*) from public.projects) projects,(select count(*) from public.cells) cells,(select count(*) from public.dragon_cycles) cycles;
set role authenticated;select set_config('request.jwt.claim.sub','91600000-0000-4000-8000-000000000001',true);
create temporary table registered_agent as select public.register_preproject_ai_agent((select subject from fixture)) result;grant select on registered_agent to authenticated;
select is((select kind from public.actors where id=(select (result->>'agent_actor_id')::uuid from registered_agent)),'AI_AGENT','Human can activate a preproject AI Actor without Project');
select ok(exists(select 1 from public.actor_memberships where actor_id=(select (result->>'agent_actor_id')::uuid from registered_agent) and profile_id='91600000-0000-4000-8000-000000000001' and role='OPERATOR'),'AI Actor preserves its exact Human operator');
create temporary table replayed_agent as select public.register_preproject_ai_agent((select subject from fixture)) result;grant select on replayed_agent to authenticated;
select is((select result->>'agent_actor_id' from replayed_agent),(select result->>'agent_actor_id' from registered_agent),'activation replay returns the exact same AI Actor');
select is((select (result->>'replayed')::boolean from replayed_agent),true,'activation replay is explicit');
select is((select count(*)::int from public.actors where kind='AI_AGENT' and operator_profile_id='91600000-0000-4000-8000-000000000001' and operator_label='CZ_PREPROJECT_PRIVATE_INTERPRETER'),1,'unique invariant permits one private interpreter under concurrent activation');
create temporary table input as select public.record_preproject_human_text((select subject from fixture),'ORIGINAL_RECORD','Only this exact private text.','{"test":true}') result;grant select on input to authenticated;
create temporary table selection as select jsonb_build_array(jsonb_build_object('record_id',result->>'record_id','record_class','ORIGINAL_RECORD','content_sha256',result->>'content_sha256')) inputs from input;grant select on selection to authenticated;
create temporary table enqueued as select public.authorize_and_enqueue_preproject_ai_execution((select subject from fixture),(select subject from fixture),(select inputs from selection),'One bounded durable interpretation','91600000-0000-4000-8000-0000000000aa','MOCK','deterministic-v1',128,0.01,'durable-test-idempotency') result;grant select on enqueued to authenticated,move2_vs1_worker;
select is((select state from public.ai_executions),'QUEUED','durable execution is queued');
select is((select count(*)::int from public.preproject_interpretation_authorizations),1,'one atomic Human command creates one authorization');
select is((select max_calls from public.ai_executions),1,'auth_receipt permits exactly one call');
select is((select max_output_tokens from public.ai_executions),128::bigint,'output generation limit is durable');
select is((select max_spend_usd from public.ai_executions),0.01::numeric,'post-execution spend ceiling is durable');
select throws_ok('select * from private.ai_execution_requests','42501',null,'Human cannot read private worker request directly');
select is((public.authorize_and_enqueue_preproject_ai_execution((select subject from fixture),(select subject from fixture),(select inputs from selection),'One bounded durable interpretation','91600000-0000-4000-8000-0000000000aa','MOCK','deterministic-v1',128,0.01,'durable-test-idempotency')->>'execution_id'),(select result->>'execution_id' from enqueued),'exact retry returns existing durable execution');
select is((select count(*)::int from public.preproject_interpretation_authorizations),1,'exact retry creates no second authorization');
select throws_ok(format('select public.authorize_and_enqueue_preproject_ai_execution(%L::uuid,%L::uuid,%L::jsonb,%L,%L::uuid,%L,%L,%s,%s,%L)',(select subject from fixture),(select subject from fixture),(select inputs::text from selection),'One bounded durable interpretation','91600000-0000-4000-8000-0000000000aa','MOCK','deterministic-v1',256,0.01,'durable-test-idempotency'),'P0001','CZ409:AI_EXECUTION_IDEMPOTENCY_CONFLICT','same command with altered terms fails closed');
select is((select count(*)::int from public.preproject_interpretation_authorizations),1,'failed altered retry leaves no false authorization');
select set_config('request.jwt.claim.sub','91600000-0000-4000-8000-000000000002',true);
select is((select count(*)::int from public.ai_executions),0,'unrelated Human cannot read execution');
select throws_ok(format('select public.register_preproject_ai_agent(%L::uuid)',(select subject from fixture)),'42501','CZ403:CONTROLLED_HUMAN_REQUESTER_REQUIRED','unrelated Human cannot activate or control subject interpreter');
reset role;
select is(has_table_privilege('move2_vs1_worker','public.preproject_records','SELECT'),false,'worker cannot browse Human records');
set local role move2_vs1_worker;
create temporary table claim as select private.move2_worker_claim(30) result;grant select on claim to move2_vs1_worker;
create temporary table dispatch as select private.preproject_worker_begin_dispatch((result->>'execution_id')::uuid,(result->>'claim_token')::uuid,'91600000-0000-4000-8000-0000000000f1') result from claim;grant select on dispatch to move2_vs1_worker;
create temporary table completed as select private.preproject_worker_complete_mock((select (result->>'execution_id')::uuid from claim),(select (result->>'claim_token')::uuid from claim),'91600000-0000-4000-8000-0000000000f1','Durable deterministic output.','71a86e332ac1a5f567a1f66abd0a33a1de54d151929556ea7bbab476fadfdfbe',(select (result->>'message_id')::bigint from claim)) result;
reset role;
select is((select result->>'provider' from dispatch),'MOCK','shared worker claims preproject execution');
select ok((select result->>'request_canonical' like '%Only this exact private text.%' from dispatch),'worker receives exact prepared selected text');
select is((select result->>'request_digest' from dispatch),(select request_digest from public.ai_executions where id=(select (result->>'execution_id')::uuid from claim)),'worker request digest round-trips');
select is((select state from public.ai_executions where id=(select (result->>'execution_id')::uuid from claim)),'SUCCEEDED','controlled worker completes durable execution');
select is((select execution_class from public.preproject_candidate_interpretations where execution_id=(select (result->>'execution_id')::uuid from claim)),'SYNTHETIC_TEST_OUTPUT','MOCK remains visibly synthetic');
select is((select actual_producer_actor_id from public.preproject_candidate_interpretations where execution_id=(select (result->>'execution_id')::uuid from claim)),null,'MOCK does not fabricate actual AI producer');
select is((select execution_id from public.preproject_candidate_interpretations where execution_id=(select (result->>'execution_id')::uuid from claim)),(select id from public.ai_executions where id=(select (result->>'execution_id')::uuid from claim)),'candidate references execution receipt');
select is((select human_adoption_state from public.preproject_candidate_interpretations where execution_id=(select (result->>'execution_id')::uuid from claim)),'NOT_HUMAN_ADOPTED','execution never adopts candidate');
select is((select count(*) from public.projects),(select projects from baseline),'no fake Project');
select is((select count(*) from public.cells),(select cells from baseline),'no fake Cell');
select is((select count(*) from public.dragon_cycles),(select cycles from baseline),'no fake Dragon Cycle');

set role authenticated;select set_config('request.jwt.claim.sub','91600000-0000-4000-8000-000000000001',true);
create temporary table provider_enqueued as select public.authorize_and_enqueue_preproject_ai_execution((select subject from fixture),(select subject from fixture),(select inputs from selection),'Token semantics','91600000-0000-4000-8000-0000000000aa','moonshotai','moonshotai/kimi-k2.6',5,0.01,'provider-token-semantics') result;grant select on provider_enqueued to authenticated,move2_vs1_worker;
reset role;set role move2_vs1_worker;
create temporary table provider_claim as select private.move2_worker_claim(30) result;grant select on provider_claim to move2_vs1_worker;
create temporary table provider_dispatch as select private.preproject_worker_begin_dispatch((result->>'execution_id')::uuid,(result->>'claim_token')::uuid,'91600000-0000-4000-8000-0000000000f2') result from provider_claim;grant select on provider_dispatch to move2_vs1_worker;
select private.preproject_worker_complete_provider((select (result->>'execution_id')::uuid from provider_claim),(select (result->>'claim_token')::uuid from provider_claim),'91600000-0000-4000-8000-0000000000f2','12345','5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5',100,5,105,0.001,'PROVIDER_REPORTED',(select (result->>'message_id')::bigint from provider_claim));
reset role;
select is((select state from public.ai_executions where id=(select (result->>'execution_id')::uuid from provider_claim)),'SUCCEEDED','input plus output may exceed output limit when output respects it');
select is((select total_tokens from public.ai_executions where id=(select (result->>'execution_id')::uuid from provider_claim)),105::bigint,'input output and total observations remain independent');
set role authenticated;select set_config('request.jwt.claim.sub','91600000-0000-4000-8000-000000000001',true);
create temporary table overlimit_enqueued as select public.authorize_and_enqueue_preproject_ai_execution((select subject from fixture),(select subject from fixture),(select inputs from selection),'Output over-limit test','91600000-0000-4000-8000-0000000000aa','moonshotai','moonshotai/kimi-k2.6',4,0.01,'provider-output-overlimit') result;grant select on overlimit_enqueued to authenticated,move2_vs1_worker;
reset role;set role move2_vs1_worker;
create temporary table overlimit_claim as select private.move2_worker_claim(30) result;grant select on overlimit_claim to move2_vs1_worker;
select private.preproject_worker_begin_dispatch((select (result->>'execution_id')::uuid from overlimit_claim),(select (result->>'claim_token')::uuid from overlimit_claim),'91600000-0000-4000-8000-0000000000f3');
reset role;
select throws_ok(format('select private.preproject_worker_complete_provider(%L::uuid,%L::uuid,%L::uuid,%L,%L,%s,%s,%s,%s,%L,%s)',(select result->>'execution_id' from overlimit_claim),(select result->>'claim_token' from overlimit_claim),'91600000-0000-4000-8000-0000000000f3','12345','5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5',1,5,6,0.001,'PROVIDER_REPORTED',(select result->>'message_id' from overlimit_claim)),'22023','CZ422:AI_EXECUTION_RESULT_MISMATCH','observed output above authorized output limit fails closed');
select * from finish();rollback;
