// SPDX-License-Identifier: MPL-2.0
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { homedir } from "node:os";
import { join } from "node:path";
import { listLocalModels } from "./ollama-local";

const execFileAsync = promisify(execFile);
export type CapabilityAvailability = "AVAILABLE_NOW" | "AVAILABLE_WITH_EXISTING_AUTH" | "LOCAL_ONLY" | "REFERENCE_ONLY" | "BLOCKED" | "UNAVAILABLE";
export interface HabitatCapability {
  id: string;
  name: string;
  kind: "HUMAN" | "INSTITUTIONAL" | "INTELLIGENCE" | "EXECUTOR" | "KNOWLEDGE" | "DIGITAL";
  source: string;
  effect: string;
  availability: CapabilityAvailability;
  conditions: string[];
  authorityRequirement: string;
  riskReversibility: string;
  provenanceStatus: string;
}

export type CurrentCapabilityAvailability = "AVAILABLE" | "AVAILABLE_WITH_HUMAN_CONFIRMATION" | "BACKGROUND_ONLY" | "CONFIGURED_BUT_UNAVAILABLE" | "NOT_CONFIGURED" | "HISTORICAL_ONLY";
export interface CurrentCapability {
  id: string;
  label: string;
  enables: string;
  readWrite: "READ_ONLY" | "DRAFT_ONLY" | "DIRECT_HUMAN_WRITE" | "WRITE_AFTER_HUMAN_CONFIRMATION";
  authorityRequired: string;
  costUsageClass: string;
  availability: CurrentCapabilityAvailability;
  reason: string;
  actionEntrypoint: string | null;
}

export function projectCurrentCapabilities(input: {
  codexAuthenticated: boolean;
  localModelInstalled: boolean;
  hulyConfigured: boolean;
  hasOpenWork: boolean;
  hasIntentions: boolean;
  hasProjects: boolean;
  hasOpenOpportunities: boolean;
  hasSubmittedProposals: boolean;
  hasCommitments: boolean;
  hasEvidenceEligibleClaims: boolean;
  hasCompletedWork: boolean;
  hasEligibleExecutionAgreement: boolean;
}): CurrentCapability[] {
  return [
    { id: "cz:read-current-state", label: "Ler o contexto da Célula", enables: "Reconstruir Person, Cell, relação, trabalho e continuidade local autorizada.", readWrite: "READ_ONLY", authorityRequired: "Sessão CZ válida e cell.read resolvida no servidor.", costUsageClass: "Sem chamada externa por si só.", availability: "AVAILABLE", reason: "Contexto local derivado do FoundationStore; fonte canônica e direção local ficam separadas.", actionEntrypoint: "/" },
    { id: "cz:locate-work", label: "Encontrar e abrir trabalho", enables: input.hasOpenWork ? "Localizar os Works abertos reais e criar um deep link validado." : "Abrir a área de trabalho quando existir um Work.", readWrite: "READ_ONLY", authorityRequired: "Sessão CZ válida; IDs são selecionados somente do contexto autorizado.", costUsageClass: "Sem chamada externa por si só.", availability: input.hasOpenWork ? "AVAILABLE" : "CONFIGURED_BUT_UNAVAILABLE", reason: input.hasOpenWork ? "Há Work aberto no estado durável local." : "Não há Work aberto no estado local atual.", actionEntrypoint: "/cells" },
    { id: "cz:create-work", label: "Propor e criar um Work", enables: "Preparar Work a partir da conversa e criar somente após confirmação humana.", readWrite: "WRITE_AFTER_HUMAN_CONFIRMATION", authorityRequired: "Confirmação explícita e cell.update verificado no servidor.", costUsageClass: "Persistência local; interpretação pode consumir quota da conta conectada.", availability: "AVAILABLE_WITH_HUMAN_CONFIRMATION", reason: "A criação passa pelo Action Gateway; a proposta do modelo não grava estado.", actionEntrypoint: "/conversations" },
    { id: "cz:create-project", label: "Dar coordenação durável a uma intenção", enables: "Criar Project ligado ao Original Record de intenção, preservando sua origem.", readWrite: "WRITE_AFTER_HUMAN_CONFIRMATION", authorityRequired: "Confirmação humana e cell.update verificado no servidor.", costUsageClass: "Persistência local; sem chamada externa por si só.", availability: input.hasIntentions ? "AVAILABLE_WITH_HUMAN_CONFIRMATION" : "CONFIGURED_BUT_UNAVAILABLE", reason: input.hasIntentions ? "Há intenções atribuídas que podem ser coordenadas; Project é opcional." : "Requer uma intenção atribuída ainda não transformada em Project.", actionEntrypoint: "/cells" },
    { id: "cz:open-opportunity", label: "Abrir uma possibilidade com condições", enables: "Registrar condições e resultado esperado dentro de um Project.", readWrite: "WRITE_AFTER_HUMAN_CONFIRMATION", authorityRequired: "Confirmação humana e cell.update verificado no servidor.", costUsageClass: "Persistência local; nenhum fundo é movimentado.", availability: input.hasProjects ? "AVAILABLE_WITH_HUMAN_CONFIRMATION" : "CONFIGURED_BUT_UNAVAILABLE", reason: input.hasProjects ? "Project local disponível; a possibilidade só existe após revisão humana." : "Requer Project existente; não criamos um apenas para habilitar esta ação.", actionEntrypoint: "/cells" },
    { id: "cz:submit-proposal", label: "Propor como atender uma possibilidade", enables: "Enviar abordagem, condições e entrega esperada para decisão legítima.", readWrite: "WRITE_AFTER_HUMAN_CONFIRMATION", authorityRequired: "Confirmação do autor; aceitação posterior exige authority CZ.", costUsageClass: "Persistência local; não cria obrigação econômica.", availability: input.hasOpenOpportunities ? "AVAILABLE_WITH_HUMAN_CONFIRMATION" : "CONFIGURED_BUT_UNAVAILABLE", reason: input.hasOpenOpportunities ? "Há oportunidade aberta; proposta e Commitment permanecem distintos." : "Requer Opportunity aberta em Project existente.", actionEntrypoint: "/cells" },
    { id: "cz:decide-proposal", label: "Aceitar ou recusar uma proposta", enables: "Registrar decisão humana atribuída; aceitação pode criar Commitment com versões congeladas.", readWrite: "WRITE_AFTER_HUMAN_CONFIRMATION", authorityRequired: "Human com cell.update resolvido no servidor; não é consenso automático.", costUsageClass: "Persistência local; sem obrigação econômica automática.", availability: input.hasSubmittedProposals ? "AVAILABLE_WITH_HUMAN_CONFIRMATION" : "CONFIGURED_BUT_UNAVAILABLE", reason: input.hasSubmittedProposals ? "Existe proposta submetida aguardando decisão." : "Nenhuma proposta submetida aguarda decisão no estado atual.", actionEntrypoint: "/cells" },
    { id: "cz:define-agreement", label: "Definir um acordo operacional", enables: "Explicitar escopo, exclusões, dependências e critério de avaliação após Commitment.", readWrite: "WRITE_AFTER_HUMAN_CONFIRMATION", authorityRequired: "Confirmação humana com cell.update; acordo não cria direito econômico oculto.", costUsageClass: "Persistência local; sem movimentação de fundos.", availability: input.hasCommitments ? "AVAILABLE_WITH_HUMAN_CONFIRMATION" : "CONFIGURED_BUT_UNAVAILABLE", reason: input.hasCommitments ? "Commitment disponível; Agreement é separado e termos econômicos não são inferidos." : "Requer Commitment aceito; nenhum está presente agora.", actionEntrypoint: "/cells" },
    { id: "cz:record-human-decision", label: "Registrar uma decisão humana", enables: "Atribuir pergunta, alternativas, fontes e consequência desejada a quem decidiu.", readWrite: "DIRECT_HUMAN_WRITE", authorityRequired: "Authority CZ é resolvida no servidor; decisão individual não é chamada de consenso.", costUsageClass: "Persistência local; sem inferência obrigatória.", availability: "AVAILABLE", reason: "A pessoa pode registrar a decisão diretamente; propostas de IA não a substituem.", actionEntrypoint: "/cells" },
    { id: "cz:record-work-learning", label: "Registrar resultado e aprendizado do trabalho", enables: "Concluir Work com consequência atribuída e registrar o que mudou/aprendeu.", readWrite: "DIRECT_HUMAN_WRITE", authorityRequired: "Person autenticada e cell.update; resultado continua sendo relato atribuível.", costUsageClass: "Persistência local; sem inferência obrigatória.", availability: input.hasOpenWork ? "AVAILABLE" : "CONFIGURED_BUT_UNAVAILABLE", reason: input.hasOpenWork ? "Há Work aberto e a pessoa pode relatar conclusão e aprendizado." : input.hasCompletedWork ? "Não há Work aberto; trabalhos concluídos permanecem disponíveis para refletir capacidade." : "Requer Work aberto para registrar uma consequência de conclusão.", actionEntrypoint: "/cells" },
    { id: "cz:attach-attributed-evidence", label: "Ligar artefato a uma afirmação", enables: "Anexar artefato a Claim com limitações explícitas; isso não verifica a afirmação.", readWrite: "WRITE_AFTER_HUMAN_CONFIRMATION", authorityRequired: "Human com authority CZ; verificação independente exige outra pessoa legítima.", costUsageClass: "Persistência local; sem verificador ou serviço externo inventado.", availability: input.hasEvidenceEligibleClaims ? "AVAILABLE_WITH_HUMAN_CONFIRMATION" : "CONFIGURED_BUT_UNAVAILABLE", reason: input.hasEvidenceEligibleClaims ? "Claim com artefato elegível está presente; link permanece evidência atribuída." : "Requer Claim e artefato ligados a contribuição existente; nenhum par elegível foi encontrado.", actionEntrypoint: "/cells" },
    { id: "cz:capability-growth", label: "Refletir sobre uma capacidade que cresceu", enables: "Propor CapabilityCandidate ligado ao aprendizado de Work concluído; pessoa revisa antes de aceitar.", readWrite: "WRITE_AFTER_HUMAN_CONFIRMATION", authorityRequired: "Atribuição e confirmação da pessoa; capacidade permanece não verificada.", costUsageClass: "Persistência local; sem chamada de modelo necessária.", availability: input.hasCompletedWork ? "AVAILABLE_WITH_HUMAN_CONFIRMATION" : "CONFIGURED_BUT_UNAVAILABLE", reason: input.hasCompletedWork ? "Aprendizado de Work concluído pode sustentar uma proposta, sem provar competência." : "Requer Work concluído e aprendizado atribuível.", actionEntrypoint: "/cells" },
    { id: "cz:profile-manual", label: "Editar seu perfil", enables: "Editar diretamente os campos de perfil expostos pela superfície Você.", readWrite: "DIRECT_HUMAN_WRITE", authorityRequired: "Ação direta do Person autenticado.", costUsageClass: "Persistência local; sem chamada de modelo.", availability: "AVAILABLE", reason: "A edição manual não depende de Essenthius.", actionEntrypoint: "/you" },
    { id: "essenthius:model-control", label: "Escolher provider por conversa", enables: "Selecionar Codex ou AUTO para o thread; mudança de preferência não altera identidade nem cria turno.", readWrite: "DIRECT_HUMAN_WRITE", authorityRequired: "Escolha direta do Human autenticado; Codex exige sessão existente; inferência local interativa segue indisponível.", costUsageClass: "A preferência não consome quota; cada chamada pode consumir limites da conta conectada.", availability: "AVAILABLE", reason: input.codexAuthenticated ? "AUTO e Codex podem ser escolhidos; provider/modelo usado é mostrado por resposta." : "AUTO e provider autenticado quando disponível; provider não autenticado não é anunciado como utilizável.", actionEntrypoint: "/conversations" },
    { id: "cz:profile-assist", label: "Preparar mudança de perfil com Essenthius", enables: "Produzir um rascunho sustentado por fontes para revisão seletiva.", readWrite: "DRAFT_ONLY", authorityRequired: "Só campos aceitos pelo Human alteram o Profile.", costUsageClass: input.codexAuthenticated ? "Quota da conta Codex existente; custo monetário desconhecido." : "Indisponível sem provider autenticado.", availability: input.codexAuthenticated ? "AVAILABLE_WITH_HUMAN_CONFIRMATION" : "CONFIGURED_BUT_UNAVAILABLE", reason: input.codexAuthenticated ? "Rascunho não altera o perfil até aceitação por campo." : "Codex não está autenticado neste processo.", actionEntrypoint: "/you" },
    { id: "cz:experience-draft", label: "Registrar uma experiência relatada", enables: "Preparar um rascunho de Experience a partir da fala, mantendo data/fatos não informados como incerteza.", readWrite: "WRITE_AFTER_HUMAN_CONFIRMATION", authorityRequired: "Revisão explícita e confirmação humana antes de persistir.", costUsageClass: input.codexAuthenticated ? "Quota da conta Codex existente; sem chamada de API paga direta." : "Provider interativo não disponível.", availability: input.codexAuthenticated ? "AVAILABLE_WITH_HUMAN_CONFIRMATION" : "CONFIGURED_BUT_UNAVAILABLE", reason: "ConversationMessage e Experience/OriginalRecord permanecem semânticas distintas.", actionEntrypoint: "/you" },
    { id: "cz:meeting", label: "Preparar um encontro com Essenthius", enables: "Propor e, após confirmação, abrir uma sala textual persistente com Marcos e Essenthius.", readWrite: "WRITE_AFTER_HUMAN_CONFIRMATION", authorityRequired: "Confirmação humana; nenhum participante não observado é inventado.", costUsageClass: "Persistência local; cada interpretação pode consumir quota da conta conectada.", availability: "AVAILABLE_WITH_HUMAN_CONFIRMATION", reason: "Sala textual, sem prometer áudio/vídeo.", actionEntrypoint: "/meetings" },
    { id: "essenthius:codex-interpretation", label: "Interpretar e compor contexto", enables: "Responder em conversa usando contexto CZ limitado; Codex é provider substituível, não identidade nem executor.", readWrite: "READ_ONLY", authorityRequired: "Nenhuma autoridade institucional; saída é Interpretation/proposta.", costUsageClass: input.codexAuthenticated ? "Quota dos limites da conta ChatGPT/Codex; custo monetário por chamada não disponível." : "Provider interativo indisponível.", availability: input.codexAuthenticated ? "AVAILABLE" : "CONFIGURED_BUT_UNAVAILABLE", reason: input.codexAuthenticated ? "Codex CLI autenticado; chamada normal anterior foi persistida." : "Sessão CLI não autenticada para este processo.", actionEntrypoint: "/conversations" },
    { id: "executor:codex-cli", label: "Executar uma tarefa de software delimitada", enables: "Rodar Codex via Execution Fabric em checkout limpo e isolado e devolver um Result Package.", readWrite: "WRITE_AFTER_HUMAN_CONFIRMATION", authorityRequired: "Commitment/Agreement elegível, escopo exato e autorização específica do Human.", costUsageClass: "Quota da conta Codex conectada; sem commit/push/PR/merge/deploy.", availability: input.hasEligibleExecutionAgreement && input.codexAuthenticated ? "AVAILABLE_WITH_HUMAN_CONFIRMATION" : "CONFIGURED_BUT_UNAVAILABLE", reason: input.hasEligibleExecutionAgreement ? (input.codexAuthenticated ? "Execução ainda exige autorização específica." : "Codex CLI sem autenticação neste processo.") : "A capacidade e o Execution Fabric existem, mas o estado local não contém Agreement elegível; não fabricamos autorização.", actionEntrypoint: "/cells" },
    { id: "provider:ollama-local", label: "Usar inferência local em tarefa de fundo", enables: "Tentar síntese/classificação que não bloqueia a interação.", readWrite: "READ_ONLY", authorityRequired: "Nenhuma autoridade; saída continua sendo proposta.", costUsageClass: "Compute local, sem token remoto; latência interativa observada é inadequada neste host.", availability: input.localModelInstalled ? "BACKGROUND_ONLY" : "CONFIGURED_BUT_UNAVAILABLE", reason: input.localModelInstalled ? "Modelo presente; demora medida impede uso como resposta interativa padrão." : "Modelo local selecionado não está instalado/disponível.", actionEntrypoint: null },
    { id: "provider:kimi", label: "Raciocínio remoto Kimi", enables: "Poderia fornecer uma rota remota alternativa.", readWrite: "READ_ONLY", authorityRequired: "Nenhuma autoridade institucional.", costUsageClass: "Chamada potencialmente paga; permanece sem configuração e sem uso.", availability: "NOT_CONFIGURED", reason: "Não há configuração/credencial lida; nenhuma chamada será feita.", actionEntrypoint: null },
    { id: "auth:huly", label: "Entrar e recuperar a sessão CZ", enables: "Usar Huly Accounts como autenticação técnica e resolver a IdentityCredential para Person CZ.", readWrite: "READ_ONLY", authorityRequired: "Person/relação/authority CZ são resolvidas separadamente no servidor.", costUsageClass: "Stack local; nenhum provedor externo de inferência.", availability: input.hulyConfigured ? "AVAILABLE" : "CONFIGURED_BUT_UNAVAILABLE", reason: input.hulyConfigured ? "Endpoint local de auth está configurado; Account não é Person nem prova identidade externa." : "Endpoint local de autenticação não está configurado neste processo.", actionEntrypoint: "/" },
    { id: "cz:snapshot-recovery", label: "Exportar e recuperar estado local", enables: "Exportar snapshot; recuperação requer validação, backup e confirmação explícita.", readWrite: "WRITE_AFTER_HUMAN_CONFIRMATION", authorityRequired: "Exportação pela sessão; restore exige autoridade CZ e confirmação explícita após dry-run.", costUsageClass: "Operação local, sem serviço externo.", availability: "AVAILABLE_WITH_HUMAN_CONFIRMATION", reason: "Snapshot/restore usam caminho local e cópia de segurança; restore não é merge automático.", actionEntrypoint: "/you" },
    { id: "cz:historical-project-economy", label: "Economia remota histórica", enables: "Consultar semânticas de economia histórica somente como fonte de domínio.", readWrite: "READ_ONLY", authorityRequired: "Nenhum dado remoto é lido ou alterado neste Habitat.", costUsageClass: "Sem chamada externa; integração ao estado local não estabelecida.", availability: "HISTORICAL_ONLY", reason: "Os contratos remotos históricos existem, mas não estão conectados aos registros deste Habitat local.", actionEntrypoint: null },
  ];
}

export async function codexCliAuthenticated() {
  try {
    const executable = process.env.CZ_CODEX_BIN ?? join(homedir(), ".local", "bin", "codex");
    const result = await execFileAsync(executable, ["login", "status"], { timeout: 2500, maxBuffer: 4096 });
    return { available: /logged in|authenticated/i.test(`${result.stdout}\n${result.stderr}`), authMode: "ChatGPT CLI session" };
  } catch {
    return { available: false, authMode: "unknown" };
  }
}

export async function discoverHabitatCapabilities(experiences: Array<{ id: string; title: string; provenance: string }> = []) {
  const [localModels, codex] = await Promise.all([listLocalModels(), codexCliAuthenticated()]);
  const selectedLocalModel = process.env.CZ_LOCAL_ESSENTHIUS_MODEL ?? "qwen3:4b";
  const modelReady = localModels.models.includes(selectedLocalModel);
  const codexUsable = codex.available;
  const capabilities: HabitatCapability[] = [
    { id: "human:founder-steward", name: "Marcos · Founder / Steward", kind: "HUMAN", source: "durable CZ relations, membership and authority", effect: "Human judgment, confirmation, correction and interruption", availability: "AVAILABLE_NOW", conditions: ["Each institutional action requires an explicit human action."], authorityRequirement: "CZ membership + cell-scoped authority resolved server-side", riskReversibility: "Actions are attributable; work completion can be followed by a new record, originals are preserved.", provenanceStatus: "LOCAL_DURABLE_CZ_STATE" },
    { id: "cz:foundation-store", name: "Foundation local", kind: "INSTITUTIONAL", source: "FoundationStore / SQLite on loopback", effect: "Persist Person, Profile, Cell, records, work and return continuity", availability: "LOCAL_ONLY", conditions: ["Local machine and existing SQLite state must remain available."], authorityRequirement: "Authenticated Huly Account subject resolves one active CZ IdentityCredential and Person", riskReversibility: "Local-only state; export is available; no remote replication.", provenanceStatus: "IMPLEMENTED_LOCAL_CANDIDATE" },
    { id: "cz:records", name: "Original Records and interpretations", kind: "KNOWLEDGE", source: "@cz/records + Foundation records", effect: "Preserve attributable input separately from model interpretation", availability: "AVAILABLE_NOW", conditions: ["Visibility and source links are preserved."], authorityRequirement: "Actor derived from authenticated local session", riskReversibility: "Append-only original records.", provenanceStatus: "IMPLEMENTED_LOCAL_CANDIDATE" },
    { id: "provider:ollama-local", name: `Modelo local (${selectedLocalModel})`, kind: "INTELLIGENCE", source: "Ollama loopback API / locally installed model", effect: "Interpret, compose, explain and reflect over the supplied CZ context", availability: modelReady ? "BLOCKED" : "UNAVAILABLE", conditions: modelReady ? ["One bounded real interpretation took 137.15 seconds after the Huly stack was paused; insufficient for the interactive default on this Mac.", "Can be selected explicitly with CZ_ESSENTHIUS_PROVIDER=ollama-local; local CPU/RAM only."] : ["Selected model is not present in local Ollama."], authorityRequirement: "No authority; model output is interpretation/proposal only", riskReversibility: "No API charge; local CPU/RAM and output review required.", provenanceStatus: modelReady ? "MODEL_PRESENT_BUT_INTERACTIVE_LATENCY_INSUFFICIENT" : "NOT_AVAILABLE" },
    { id: "provider:codex-cli", name: "Interpretação pelo Codex autenticado", kind: "INTELLIGENCE", source: "Codex CLI / sessão ChatGPT existente; tools, shell, web search e plugins desativados para esta chamada", effect: "Interpret, compose, explain and reflect over the supplied CZ context", availability: codex.available ? "AVAILABLE_WITH_EXISTING_AUTH" : "UNAVAILABLE", conditions: [codex.authMode, "O contexto relevante desta conversa é enviado ao serviço autenticado ChatGPT/Codex; aplicam-se limites de uso do plano.", "Sem shell, agentes, web search, view-image, plugins, execução ou autoridade CZ; falhas não repetem automaticamente."], authorityRequirement: "No authority; model output is interpretation/proposal only", riskReversibility: "Nenhuma API key de cobrança é usada; o consumo fica sujeito aos limites da conta ChatGPT/Codex.", provenanceStatus: codex.available ? "CHATGPT_AUTH_READBACK; TEXT_ONLY_FLAGS_CONFIGURED" : "NOT_AUTHENTICATED" },
    { id: "executor:codex-cli", name: "Codex CLI", kind: "EXECUTOR", source: "Authenticated Codex CLI + tools/cz-execution-fabric.mjs", effect: "Bounded software task execution from a Task Capsule/work packet", availability: !codex.available ? "UNAVAILABLE" : codexUsable ? "AVAILABLE_WITH_EXISTING_AUTH" : "BLOCKED", conditions: [codex.authMode, "Cada execução cria checkout Git detached e limpo numa pasta temporária, sem tocar no worktree Habitat.", "Exige Commitment ativo, autorização humana explícita, caminhos de arquivo exatos e validações; não faz merge/push/PR/deploy."], authorityRequirement: "Stewardship CZ resolvida no servidor + confirmação específica da execução + Execution Fabric", riskReversibility: "Workspace temporário isolado; delta e Result Package ficam preservados para revisão; nenhuma promoção Git.", provenanceStatus: codex.available ? "CLI_AUTH_READBACK; EXECUTION_NOT_PERFORMED" : "CLI_AUTH_UNAVAILABLE; EXECUTION_NOT_PERFORMED" },
    { id: "source:canonical-cz", name: "Célula Zero canonical source", kind: "KNOWLEDGE", source: "Current checkout HEAD / STATE.md and decisions", effect: "Read canonical software and human-direction references", availability: "AVAILABLE_NOW", conditions: ["This checkout's HEAD is 50b4917593b0979d5c218c725038bf89afb1134f; working tree contains local candidate changes."], authorityRequirement: "Read-only source; Git text is not automatically institutional truth", riskReversibility: "Read-only", provenanceStatus: "LOCAL_HEAD_READBACK; ORIGIN_NOT_RECHECKED_THIS_TURN" },
    { id: "auth:huly", name: "Huly Accounts", kind: "DIGITAL", source: "CZ_HULY_ACCOUNTS_URL loopback adapter", effect: "Authenticate local entry and supply stable Account.uuid subject", availability: process.env.CZ_HULY_ACCOUNTS_URL ? "LOCAL_ONLY" : "UNAVAILABLE", conditions: ["Authentication only; Account is not Person and proves no external identity."], authorityRequirement: "CZ identity credential + relation/authority separately resolved", riskReversibility: "Local adapter; no Huly Workbench or domain persistence used by CZ.", provenanceStatus: process.env.CZ_HULY_ACCOUNTS_URL ? "CONFIGURED_LOCAL_ADAPTER" : "NOT_CONFIGURED" },
    { id: "platform:supabase", name: "Supabase historical substrate", kind: "DIGITAL", source: "apps/web / existing migrations and Company Core", effect: "Historical Auth/Postgres and project/work capabilities", availability: "REFERENCE_ONLY", conditions: ["Not used by this local Habitat; no remote operations authorized."], authorityRequirement: "Historical CZ server-side auth/RLS boundaries; needs a separately reviewed adapter", riskReversibility: "Would introduce remote state and expand scope", provenanceStatus: "HISTORICAL_CAPABILITY_NOT_COMPOSED_HERE" },
    { id: "executor:task-capsule", name: "Task Capsule / Result Package", kind: "INSTITUTIONAL", source: "apps/web/lib/domain/task-capsule.ts and result-package.ts", effect: "Portable task scope and attributable result boundary", availability: "AVAILABLE_NOW", conditions: ["Task Capsule is reconstructed from accepted CZ Commitment versions; Result Package remains executor output, not independent Verification."], authorityRequirement: "Task-specific Human authorization and executor boundary", riskReversibility: "Portable files; execution and verification remain distinct", provenanceStatus: "HISTORICAL_SEMANTICS_COMPOSED_LOCALLY" },
    { id: "cz:historical-project-opportunity", name: "Projects, Needs and Opportunities (historical CZ)", kind: "INSTITUTIONAL", source: "apps/web/lib/data/projects.ts; coordination.ts; workbench.ts", effect: "Existing CZ-owned project, opportunity, proposal and commitment semantics", availability: "REFERENCE_ONLY", conditions: ["These remote Supabase projections are not bound to the local Huly-authenticated Person or this FoundationStore."], authorityRequirement: "A separately established account-to-Person and Cell authority mapping is required before composition.", riskReversibility: "No remote read/write is performed here; semantic source remains inspectable.", provenanceStatus: "SOURCE_CODE_PRESENT; LOCAL HABITAT DATA NOT COMPOSED" },
    { id: "cz:historical-contribution-evidence", name: "Contribution, Artifact, Claim and Verification (historical CZ)", kind: "INSTITUTIONAL", source: "apps/web/lib/data/work.ts; history.ts; verifications.ts; @cz/records", effect: "Existing CZ lineage distinguishes contribution/artifact from claim/evidence/verification/decision", availability: "REFERENCE_ONLY", conditions: ["Historical Supabase data is not connected to this local Person or Cell."], authorityRequirement: "Do not adopt historical rows until their Person, Cell, visibility and authority are mapped.", riskReversibility: "No data is copied or reinterpreted; source references remain intact.", provenanceStatus: "DOMAIN SOURCE PRESENT; LIVE RECORDS NOT READ" },
  ];
  for (const experience of experiences.slice(-6)) capabilities.push({
    id: `person-experience:${experience.id}`,
    name: `Experiência relatada: ${experience.title}`,
    kind: "HUMAN",
    source: "CZ Profile / Experience com provenance user_reported",
    effect: "Contexto candidato para composição; não é capacidade verificada",
    availability: "AVAILABLE_NOW",
    conditions: ["Relato humano; usar somente como contexto e pedir confirmação quando mudar seu significado."],
    authorityRequirement: "Não concede autoridade nem prova de capacidade",
    riskReversibility: "Interpretação corrigível; perfil e Original Record permanecem separados",
    provenanceStatus: experience.provenance,
  });
  return capabilities;
}

export interface HabitatConnection {
  id: string;
  name: string;
  status: "AVAILABLE_LOCAL" | "AUTHENTICATED" | "CONFIGURED_UNVERIFIED" | "REFERENCE_ONLY" | "UNAVAILABLE" | "BLOCKED";
  source: string;
  boundary: string;
  evidence: string;
}

export function discoverHabitatConnections(input: { ollamaAvailable: boolean; selectedModelAvailable: boolean; ollamaInteractive: boolean; codexAuthenticated: boolean }) {
  return [
    { id: "connection:foundation-store", name: "Armazenamento local da Célula Zero", status: "AVAILABLE_LOCAL" as const, source: "FoundationStore / SQLite", boundary: "Somente local neste Habitat; não é armazenamento remoto da plataforma.", evidence: "A API local responde; registros da sessão permanecem no estado local." },
    { id: "connection:ollama", name: "Modelo local", status: !input.ollamaAvailable || !input.selectedModelAvailable ? "UNAVAILABLE" as const : input.ollamaInteractive ? "AVAILABLE_LOCAL" as const : "BLOCKED" as const, source: "Ollama loopback", boundary: "Inferência local; nenhuma chave ou chamada paga; latência medida nesta máquina é inadequada ao padrão interativo.", evidence: input.selectedModelAvailable ? "Modelo qwen3:4b instalado; uma interpretação estruturada levou 137.15s com o stack Huly parado." : "Endpoint/modelo não confirmado disponível." },
    { id: "connection:codex-inference", name: "Interpretação Codex", status: input.codexAuthenticated ? "AUTHENTICATED" as const : "UNAVAILABLE" as const, source: "Codex CLI com autenticação ChatGPT", boundary: "Interpretação externa; contexto CZ relevante é enviado ao serviço; ferramenta shell, web, agentes e plugins desativados. Não é o Executor Codex.", evidence: input.codexAuthenticated ? "codex login status e chamada de texto única concluída; uso sujeito aos limites ChatGPT/Codex." : "Sessão CLI não confirmada." },
    { id: "connection:codex-cli", name: "Sessão Codex", status: input.codexAuthenticated ? "AUTHENTICATED" as const : "UNAVAILABLE" as const, source: "Codex CLI local", boundary: "Autenticação não autoriza execução. A cada autorização, o adapter cria um checkout detached limpo e remove-o após preservar o delta.", evidence: input.codexAuthenticated ? "codex login status; nenhuma tarefa executada por este readback." : "Sessão CLI não confirmada." },
    { id: "connection:huly-accounts", name: "Autenticação Huly", status: process.env.CZ_HULY_ACCOUNTS_URL ? "CONFIGURED_UNVERIFIED" as const : "UNAVAILABLE" as const, source: "CZ_HULY_ACCOUNTS_URL / Accounts API", boundary: "Auth fornece subject técnico; não é Person nem autoridade CZ.", evidence: process.env.CZ_HULY_ACCOUNTS_URL ? "Endpoint configurado no processo local; não sondado por Discover." : "Endpoint não configurado." },
    { id: "connection:github", name: "Git e estado canônico", status: "REFERENCE_ONLY" as const, source: "Checkout local MMaia-jr/celula-zero", boundary: "Readback local; não há sincronização GitHub ativa neste fluxo.", evidence: "HEAD atual é exibido como referência do checkout, não como Human Direction." },
    { id: "connection:supabase-history", name: "Substrato Supabase histórico", status: "REFERENCE_ONLY" as const, source: "apps/web / Company Core histórico", boundary: "Não conectado a esta sessão local; nenhum acesso remoto realizado.", evidence: "Módulos/fonte existem no repositório; registros remotos não foram lidos." },
  ];
}

export function discoverHabitatResources(input: { personId: string; cellId: string; openWorkIds: string[]; recordIds: string[]; head: string; projects?: Array<{ id: string; title: string; opportunities: Array<{ id: string; title: string; state: string }>; commitments: Array<{ id: string; proposalId: string; opportunityId: string }>; contributions: Array<{ id: string; commitmentId: string }> }> }) {
  return [
    { id: `person:${input.personId}`, kind: "CZ_PERSON", source: "IdentityCredential → Person + local Profile", availability: "LOCAL_ONLY", provenance: "durable CZ identity readback" },
    { id: `cell:${input.cellId}`, kind: "CZ_CELL", source: "Cell + relation + membership + authority", availability: "LOCAL_ONLY", provenance: "durable CZ institutional state" },
    ...input.openWorkIds.map((id) => ({ id: `work:${id}`, kind: "CZ_WORK", source: "local Work projection", availability: "LOCAL_ONLY", provenance: "human-attributed OriginalRecord" })),
    ...input.recordIds.slice(-8).map((id) => ({ id: `record:${id}`, kind: "CZ_RECORD", source: "local OriginalRecord/Interpretation", availability: "LOCAL_ONLY", provenance: "record class and source link preserved" })),
    ...(input.projects ?? []).flatMap((project) => [
      { id: `project:${project.id}`, kind: "CZ_PROJECT", source: project.title, availability: "LOCAL_ONLY", provenance: "CZ Workbench semantic projection; project events link to attributable Original Records" },
      ...project.opportunities.map((opportunity) => ({ id: `opportunity:${opportunity.id}`, kind: "CZ_OPPORTUNITY", source: `${project.title} · ${opportunity.title}`, availability: opportunity.state === "OPEN" ? "AVAILABLE_NOW" : "LOCAL_ONLY", provenance: "explicit project scope, conditions and expected result" })),
      ...project.commitments.map((commitment) => ({ id: `commitment:${commitment.id}`, kind: "CZ_COMMITMENT", source: `${project.title} · proposal ${commitment.proposalId}`, availability: "LOCAL_ONLY", provenance: "accepted proposal and frozen opportunity/proposal versions" })),
      ...project.contributions.map((contribution) => ({ id: `contribution:${contribution.id}`, kind: "CZ_CONTRIBUTION", source: project.title, availability: "LOCAL_ONLY", provenance: "attributable self-reported contribution; not independent verification" })),
    ]),
    { id: `repository:cz:${input.head}`, kind: "GITHUB_REPOSITORY_REFERENCE", source: "MMaia-jr/celula-zero at checkout HEAD", availability: "REFERENCE_ONLY", provenance: "local readback; no GitHub API call or external write" },
    { id: "source:cz-project-coordination", kind: "CZ_PROJECT_OPPORTUNITY_SEMANTICS", source: "apps/web/lib/data/coordination.ts and workbench.ts", availability: "REFERENCE_ONLY", provenance: "source modules exist; no historical remote rows read or linked" },
    { id: "source:cz-provenance-lineage", kind: "CZ_CONTRIBUTION_ARTIFACT_EVIDENCE", source: "apps/web/lib/data/work.ts and history.ts", availability: "REFERENCE_ONLY", provenance: "source modules exist; live institutional records are not composed here" },
  ];
}
